model_use:
  name: model_name

data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size: 64
  split_ratio: 0.8
  num_workers: 8
  random_test: False
  pin_memory: True

exp_params:
  max_epochs: 10
  LR: 0.0005
  weight_decay: 0.000001
  scheduler_gamma: 0.5
  kld_weight: 0.005
  step_size: 20
  device_type: "cuda"
  
shamir:
  num_shares: 5
  threshold: 3

logging_params:
  base_dir: "logs/"
  graph_subdir: "graphs"
  recon_subdir: "reconstructions"
  share_subdir: "shares"