model_params:
  in_channels: 3
  image_size: 128
  num_embeddings: 512      # Size of codebook (number of discrete codes)
  embedding_dim: 64        # Dimension of each code vector
  commitment_cost: 0.25    # Weight for commitment loss
  num_hiddens: 128
  num_residual_hiddens: 32
  num_residual_layers: 2
  
data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size:  64
  split_ratio: 1
  num_workers: 8
  random_test: False
  pin_memory: True

exp_params:
  max_epochs: 100
  LR: 0.001
  scheduler_gamma: 0.5
  step_size: 20
  device_type: "cuda"

shamir:
  num_shares: 5
  threshold: 3

logging_params:
  base_dir: "logs/"
  graph_subdir: "graphs"
  recon_subdir: "reconstructions"
  share_subdir: "shares"
